### ISSUE TITLE
Getting a lang from the root throws a MissingResourceException

### ISSUE THREAD

**Issue by V-ed** [Vhoyon/Discord-Bot#45]
Typing for example `lang("/vendor.lang.RequestParamStartSingle")` tries to access the vendor.lang key, which makes no sense.

```
java.util.MissingResourceException: Can't find bundle for base name vendor.lang, locale en_US
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:1573)
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1396)
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:854)
	at vendor.objects.Dictionary.getLanguageResources(Dictionary.java:253)
	at vendor.objects.Dictionary.handleResourcesUpdate(Dictionary.java:234)
	at vendor.objects.Dictionary.getString(Dictionary.java:95)
	at vendor.abstracts.Translatable.lang(Translatable.java:69)
	at commands.CommandLol.action(CommandLol.java:17)
	at app.CommandRouter.run(CommandRouter.java:168)
```

**Comment by V-ed** [comment]
Well, the problem does not happen when you put `lang("/vendor.lang.strings.RequestParamStartSingle")` which is actually very logical as taking a string with a full path makes you need to put the file name.

Now, what if we entered `lang("/vendor.lang.RequestParamStartSingle")` and actually wanted the key `RequestParamStartSingle` in the file `strings` located in `/vendor/lang/`? That premise is logical and would be nice to include. I'll work on that instead.

**Comment by V-ed** [comment]
Actually no, if a dev wants to get a string in another file than the default, let him add the whole file structure, putting a default in such a case is counter intuitive and is not even logical.
I take back I said earlier and blame that positivity on the icecream that I had taken at the same time of writing the comment.

Closing this as it pretty much is done.
